# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # O ecossistema "npm" engloba npm, yarn e pnpm. 
  # O Dependabot usará o pnpm automaticamente ao detectar o pnpm-lock.yaml.
  - package-ecosystem: "npm" 
    directory: "/" 
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: "increase"
    
    labels:
      - "dependencies"
      - "pnpm" # Etiqueta atualizada para refletir o uso do pnpm
      
    groups:
      linters-formatters:
        patterns:
          - "eslint*"
          - "prettier*"
      testing-tools:
        patterns:
          - "jest*"
          - "@testing-library*"
          - "cypress*"

  # Atualizações para as suas GitHub Actions (build.yml e deploy.yml)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      
    labels:
      - "dependencies"
      - "actions"
      
    groups:
      actions-updates:
        patterns:
          - "*"